name: TicToc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install libsdl2-dev
      run: sudo apt install libsdl2-dev 
    - name: Install libsdl2-mixer
      run: sudo apt install libsdl2-mixer-dev
    - name: Install libsdl2-image
      run: sudo apt install libsdl2-image-dev 
    - name: Install libsdl2-ttf
      run: sudo apt install libsdl2-ttf-dev 
    - name: Install libsdl2-gfx
      run: sudo apt install libsdl2-gfx-dev 
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    
    - name: Display structure of downloaded files
      run: ls -R
