name: TicToc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # install libs required by sdl2
    - name: Install libsdl2-dev
      run: sudo apt install libsdl2-dev 
    - name: Install libsdl2-mixer
      run: sudo apt install libsdl2-mixer-dev
    - name: Install libsdl2-image
      run: sudo apt install libsdl2-image-dev 
    - name: Install libsdl2-ttf
      run: sudo apt install libsdl2-ttf-dev 
    - name: Install libsdl2-gfx
      run: sudo apt install libsdl2-gfx-dev 
    - uses: actions/checkout@v2
    # build
    - name: Debug Build
      run: cargo build --verbose
    - name: Release Build
      run: cargo build --verbose --release
    # tests
    - name: Run tests
      run: cargo test --verbose
    
    # upload artifacts
    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path: target/release

